In [11]:
import tensorflow as tf

In [10]:
string = tf.Variable("I am Ash", tf.string)
number = tf.Variable(123, tf.int16)
floating = tf.Variable(3.14, tf.float64)

rank1_tensor = tf.Variable(["Test"], tf.string) # rank 1 tensor
rank2_tensor = tf.Variable([["test", "ok"], ["test", "yes"],["test", "yes"]], tf.string) # rank 2 tensor

In [8]:
print(floating)
print(rank2_tensor)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.14>
<tf.Variable 'Variable:0' shape=(3, 2) dtype=string, numpy=
array([[b'test', b'ok'],
       [b'test', b'yes'],
       [b'test', b'yes']], dtype=object)>


In [6]:

print(tf.rank(string))
print(tf.rank(floating))
print(tf.rank(rank1_tensor))
print(tf.rank(rank2_tensor))

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [29]:
shapeWithZeros = tf.zeros([3,4], tf.int16)
shapeWithOnes = tf.ones([2,3], tf.int16)

print(shapeWithZeros)
print(shapeWithOnes)

print(shapeWithZeros.shape)
print(shapeWithOnes.shape)

tf.Tensor(
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]], shape=(3, 4), dtype=int16)
tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int16)
(3, 4)
(2, 3)


In [26]:
reshaped = tf.reshape(shapeWithZeros, [2,3,2])
print(reshaped)

tf.Tensor(
[[[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]], shape=(2, 3, 2), dtype=int16)


In [27]:
reshaped2 = tf.reshape(shapeWithZeros, [4,-1])
print(reshaped2)

tf.Tensor(
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]], shape=(4, 3), dtype=int16)
