In [ ]:
import tensorflow as tf

In [2]:
string = tf.Variable("I am Ash", tf.string)
number = tf.Variable(123, tf.int16)
floating = tf.Variable(3.14, tf.float64)

rank1_tensor = tf.Variable(["Test"], tf.string)
rank2_tensor = tf.Variable([["test", "ok"], ["test", "yes"],["test", "yes"]], tf.string)

In [8]:
print(floating)
print(rank2_tensor)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.14>
<tf.Variable 'Variable:0' shape=(3, 2) dtype=string, numpy=
array([[b'test', b'ok'],
       [b'test', b'yes'],
       [b'test', b'yes']], dtype=object)>


In [6]:

print(tf.rank(string))
print(tf.rank(floating))
print(tf.rank(rank1_tensor))
print(tf.rank(rank2_tensor))

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [3]:
shapeWithZeros = tf.zeros([3,4], tf.int16)
shapeWithOnes = tf.ones([2,3], tf.int16)

In [4]:
print(shapeWithZeros)
print(shapeWithOnes)

tf.Tensor(
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]], shape=(3, 4), dtype=int16)
tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int16)
